/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CommunityAndHumanitarianRouteImport } from './routes/community-and-humanitarian'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnterpriseAndVenturesRouteImport } from './routes/enterprise-and-ventures'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LearnAndDevelopRouteImport } from './routes/learn-and-develop'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MediaAndInsightsRouteImport } from './routes/media-and-insights'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PeaceAndInstitutionalServicesRouteImport } from './routes/peace-and-institutional-services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as TravelAndPilgrimageRouteImport } from './routes/travel-and-pilgrimage'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedDispatcherRouteImport } from './routes/_authenticated/dispatcher'
import { Route as AuthenticatedDriverDispatchRouteImport } from './routes/_authenticated/driver-dispatch'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMyBarakahRouteImport } from './routes/_authenticated/my-barakah'
import { Route as AuthenticatedMyImpactRouteImport } from './routes/_authenticated/my-impact'
import { Route as AuthenticatedMyJourneyRouteImport } from './routes/_authenticated/my-journey'
import { Route as AuthenticatedMyPaymentsRouteImport } from './routes/_authenticated/my-payments'
import { Route as AuthenticatedMySupportRouteImport } from './routes/_authenticated/my-support'
import { Route as AuthenticatedMySwiftMoveRouteImport } from './routes/_authenticated/my-swift-move'
import { Route as AuthenticatedMyVehicleHiresRouteImport } from './routes/_authenticated/my-vehicle-hires'
import { Route as AuthenticatedStaffSecurityRouteImport } from './routes/_authenticated/staff-security'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as TravelSlugRouteImport } from './routes/travel.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminDispatcherRouteImport } from './routes/_authenticated/admin.dispatcher'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminSwiftMoveRouteImport } from './routes/_authenticated/admin.swift-move'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated/drive.index'
import { Route as AuthenticatedDriveWalletRouteImport } from './routes/_authenticated/drive.wallet'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedStaffAddRouteImport } from './routes/_authenticated/staff.add'
import { Route as AuthenticatedSwiftMoveNewRouteImport } from './routes/_authenticated/swift-move.new'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AuthenticatedAdminRidersIndexRouteImport } from './routes/_authenticated/admin.riders.index'
import { Route as AuthenticatedAdminRidersAddRouteImport } from './routes/_authenticated/admin.riders.add'
import { Route as AuthenticatedAdminStaffIndexRouteImport } from './routes/_authenticated/admin.staff.index'
import { Route as AuthenticatedAdminStaffAddRouteImport } from './routes/_authenticated/admin.staff.add'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminUsersCreateRouteImport } from './routes/_authenticated/admin.users.create'
import { Route as AuthenticatedAdminUsersPermissionsRouteImport } from './routes/_authenticated/admin.users.permissions'
import { Route as AuthenticatedAdminUsersRolesRouteImport } from './routes/_authenticated/admin.users.roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAndHumanitarianRoute =
  CommunityAndHumanitarianRouteImport.update({
    id: '/community-and-humanitarian',
    path: '/community-and-humanitarian',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseAndVenturesRoute = EnterpriseAndVenturesRouteImport.update({
  id: '/enterprise-and-ventures',
  path: '/enterprise-and-ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAndDevelopRoute = LearnAndDevelopRouteImport.update({
  id: '/learn-and-develop',
  path: '/learn-and-develop',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAndInsightsRoute = MediaAndInsightsRouteImport.update({
  id: '/media-and-insights',
  path: '/media-and-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PeaceAndInstitutionalServicesRoute =
  PeaceAndInstitutionalServicesRouteImport.update({
    id: '/peace-and-institutional-services',
    path: '/peace-and-institutional-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelAndPilgrimageRoute = TravelAndPilgrimageRouteImport.update({
  id: '/travel-and-pilgrimage',
  path: '/travel-and-pilgrimage',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatcherRoute = AuthenticatedDispatcherRouteImport.update({
  id: '/dispatcher',
  path: '/dispatcher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverDispatchRoute =
  AuthenticatedDriverDispatchRouteImport.update({
    id: '/driver-dispatch',
    path: '/driver-dispatch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBarakahRoute = AuthenticatedMyBarakahRouteImport.update({
  id: '/my-barakah',
  path: '/my-barakah',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyImpactRoute = AuthenticatedMyImpactRouteImport.update({
  id: '/my-impact',
  path: '/my-impact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyJourneyRoute = AuthenticatedMyJourneyRouteImport.update({
  id: '/my-journey',
  path: '/my-journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPaymentsRoute = AuthenticatedMyPaymentsRouteImport.update({
  id: '/my-payments',
  path: '/my-payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySupportRoute = AuthenticatedMySupportRouteImport.update({
  id: '/my-support',
  path: '/my-support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySwiftMoveRoute =
  AuthenticatedMySwiftMoveRouteImport.update({
    id: '/my-swift-move',
    path: '/my-swift-move',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyVehicleHiresRoute =
  AuthenticatedMyVehicleHiresRouteImport.update({
    id: '/my-vehicle-hires',
    path: '/my-vehicle-hires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffSecurityRoute =
  AuthenticatedStaffSecurityRouteImport.update({
    id: '/staff-security',
    path: '/staff-security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelSlugRoute = TravelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TravelRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDispatcherRoute =
  AuthenticatedAdminDispatcherRouteImport.update({
    id: '/admin/dispatcher',
    path: '/admin/dispatcher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/admin/emails',
    path: '/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSwiftMoveRoute =
  AuthenticatedAdminSwiftMoveRouteImport.update({
    id: '/admin/swift-move',
    path: '/admin/swift-move',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveWalletRoute =
  AuthenticatedDriveWalletRouteImport.update({
    id: '/drive/wallet',
    path: '/drive/wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffAddRoute = AuthenticatedStaffAddRouteImport.update({
  id: '/staff/add',
  path: '/staff/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwiftMoveNewRoute =
  AuthenticatedSwiftMoveNewRouteImport.update({
    id: '/swift-move/new',
    path: '/swift-move/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRidersIndexRoute =
  AuthenticatedAdminRidersIndexRouteImport.update({
    id: '/admin/riders/',
    path: '/admin/riders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRidersAddRoute =
  AuthenticatedAdminRidersAddRouteImport.update({
    id: '/admin/riders/add',
    path: '/admin/riders/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStaffIndexRoute =
  AuthenticatedAdminStaffIndexRouteImport.update({
    id: '/admin/staff/',
    path: '/admin/staff/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStaffAddRoute =
  AuthenticatedAdminStaffAddRouteImport.update({
    id: '/admin/staff/add',
    path: '/admin/staff/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersCreateRoute =
  AuthenticatedAdminUsersCreateRouteImport.update({
    id: '/admin/users/create',
    path: '/admin/users/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersPermissionsRoute =
  AuthenticatedAdminUsersPermissionsRouteImport.update({
    id: '/admin/users/permissions',
    path: '/admin/users/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRolesRoute =
  AuthenticatedAdminUsersRolesRouteImport.update({
    id: '/admin/users/roles',
    path: '/admin/users/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/community-and-humanitarian': typeof CommunityAndHumanitarianRoute
  '/contact': typeof ContactRoute
  '/enterprise-and-ventures': typeof EnterpriseAndVenturesRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn-and-develop': typeof LearnAndDevelopRoute
  '/market': typeof MarketRoute
  '/media-and-insights': typeof MediaAndInsightsRoute
  '/partners': typeof PartnersRoute
  '/peace-and-institutional-services': typeof PeaceAndInstitutionalServicesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/travel': typeof TravelRouteWithChildren
  '/travel-and-pilgrimage': typeof TravelAndPilgrimageRoute
  '/volunteer': typeof VolunteerRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/$': typeof AuthenticatedSplatRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dispatcher': typeof AuthenticatedDispatcherRoute
  '/driver-dispatch': typeof AuthenticatedDriverDispatchRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/my-barakah': typeof AuthenticatedMyBarakahRoute
  '/my-impact': typeof AuthenticatedMyImpactRoute
  '/my-journey': typeof AuthenticatedMyJourneyRoute
  '/my-payments': typeof AuthenticatedMyPaymentsRoute
  '/my-support': typeof AuthenticatedMySupportRoute
  '/my-swift-move': typeof AuthenticatedMySwiftMoveRoute
  '/my-vehicle-hires': typeof AuthenticatedMyVehicleHiresRoute
  '/staff-security': typeof AuthenticatedStaffSecurityRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/travel/$slug': typeof TravelSlugRoute
  '/admin/dispatcher': typeof AuthenticatedAdminDispatcherRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/swift-move': typeof AuthenticatedAdminSwiftMoveRoute
  '/drive/wallet': typeof AuthenticatedDriveWalletRoute
  '/staff/add': typeof AuthenticatedStaffAddRoute
  '/swift-move/new': typeof AuthenticatedSwiftMoveNewRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/admin/riders/add': typeof AuthenticatedAdminRidersAddRoute
  '/admin/staff/add': typeof AuthenticatedAdminStaffAddRoute
  '/admin/users/create': typeof AuthenticatedAdminUsersCreateRoute
  '/admin/users/permissions': typeof AuthenticatedAdminUsersPermissionsRoute
  '/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/admin/riders/': typeof AuthenticatedAdminRidersIndexRoute
  '/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/community-and-humanitarian': typeof CommunityAndHumanitarianRoute
  '/contact': typeof ContactRoute
  '/enterprise-and-ventures': typeof EnterpriseAndVenturesRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn-and-develop': typeof LearnAndDevelopRoute
  '/market': typeof MarketRoute
  '/media-and-insights': typeof MediaAndInsightsRoute
  '/partners': typeof PartnersRoute
  '/peace-and-institutional-services': typeof PeaceAndInstitutionalServicesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/travel': typeof TravelRouteWithChildren
  '/travel-and-pilgrimage': typeof TravelAndPilgrimageRoute
  '/volunteer': typeof VolunteerRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/$': typeof AuthenticatedSplatRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dispatcher': typeof AuthenticatedDispatcherRoute
  '/driver-dispatch': typeof AuthenticatedDriverDispatchRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/my-barakah': typeof AuthenticatedMyBarakahRoute
  '/my-impact': typeof AuthenticatedMyImpactRoute
  '/my-journey': typeof AuthenticatedMyJourneyRoute
  '/my-payments': typeof AuthenticatedMyPaymentsRoute
  '/my-support': typeof AuthenticatedMySupportRoute
  '/my-swift-move': typeof AuthenticatedMySwiftMoveRoute
  '/my-vehicle-hires': typeof AuthenticatedMyVehicleHiresRoute
  '/staff-security': typeof AuthenticatedStaffSecurityRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/travel/$slug': typeof TravelSlugRoute
  '/admin/dispatcher': typeof AuthenticatedAdminDispatcherRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/swift-move': typeof AuthenticatedAdminSwiftMoveRoute
  '/drive/wallet': typeof AuthenticatedDriveWalletRoute
  '/staff/add': typeof AuthenticatedStaffAddRoute
  '/swift-move/new': typeof AuthenticatedSwiftMoveNewRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/admin/riders/add': typeof AuthenticatedAdminRidersAddRoute
  '/admin/staff/add': typeof AuthenticatedAdminStaffAddRoute
  '/admin/users/create': typeof AuthenticatedAdminUsersCreateRoute
  '/admin/users/permissions': typeof AuthenticatedAdminUsersPermissionsRoute
  '/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/admin/riders': typeof AuthenticatedAdminRidersIndexRoute
  '/admin/staff': typeof AuthenticatedAdminStaffIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/community-and-humanitarian': typeof CommunityAndHumanitarianRoute
  '/contact': typeof ContactRoute
  '/enterprise-and-ventures': typeof EnterpriseAndVenturesRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn-and-develop': typeof LearnAndDevelopRoute
  '/market': typeof MarketRoute
  '/media-and-insights': typeof MediaAndInsightsRoute
  '/partners': typeof PartnersRoute
  '/peace-and-institutional-services': typeof PeaceAndInstitutionalServicesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/travel': typeof TravelRouteWithChildren
  '/travel-and-pilgrimage': typeof TravelAndPilgrimageRoute
  '/volunteer': typeof VolunteerRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/dispatcher': typeof AuthenticatedDispatcherRoute
  '/_authenticated/driver-dispatch': typeof AuthenticatedDriverDispatchRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/my-barakah': typeof AuthenticatedMyBarakahRoute
  '/_authenticated/my-impact': typeof AuthenticatedMyImpactRoute
  '/_authenticated/my-journey': typeof AuthenticatedMyJourneyRoute
  '/_authenticated/my-payments': typeof AuthenticatedMyPaymentsRoute
  '/_authenticated/my-support': typeof AuthenticatedMySupportRoute
  '/_authenticated/my-swift-move': typeof AuthenticatedMySwiftMoveRoute
  '/_authenticated/my-vehicle-hires': typeof AuthenticatedMyVehicleHiresRoute
  '/_authenticated/staff-security': typeof AuthenticatedStaffSecurityRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/travel/$slug': typeof TravelSlugRoute
  '/_authenticated/admin/dispatcher': typeof AuthenticatedAdminDispatcherRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/swift-move': typeof AuthenticatedAdminSwiftMoveRoute
  '/_authenticated/drive/wallet': typeof AuthenticatedDriveWalletRoute
  '/_authenticated/staff/add': typeof AuthenticatedStaffAddRoute
  '/_authenticated/swift-move/new': typeof AuthenticatedSwiftMoveNewRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/admin/riders/add': typeof AuthenticatedAdminRidersAddRoute
  '/_authenticated/admin/staff/add': typeof AuthenticatedAdminStaffAddRoute
  '/_authenticated/admin/users/create': typeof AuthenticatedAdminUsersCreateRoute
  '/_authenticated/admin/users/permissions': typeof AuthenticatedAdminUsersPermissionsRoute
  '/_authenticated/admin/users/roles': typeof AuthenticatedAdminUsersRolesRoute
  '/_authenticated/admin/riders/': typeof AuthenticatedAdminRidersIndexRoute
  '/_authenticated/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/community-and-humanitarian'
    | '/contact'
    | '/enterprise-and-ventures'
    | '/impact'
    | '/learn'
    | '/learn-and-develop'
    | '/market'
    | '/media-and-insights'
    | '/partners'
    | '/peace-and-institutional-services'
    | '/reset-password'
    | '/travel'
    | '/travel-and-pilgrimage'
    | '/volunteer'
    | '/what-we-do'
    | '/$'
    | '/apply'
    | '/cart'
    | '/dispatcher'
    | '/driver-dispatch'
    | '/history'
    | '/my-barakah'
    | '/my-impact'
    | '/my-journey'
    | '/my-payments'
    | '/my-support'
    | '/my-swift-move'
    | '/my-vehicle-hires'
    | '/staff-security'
    | '/learn/$slug'
    | '/share/$token'
    | '/travel/$slug'
    | '/admin/dispatcher'
    | '/admin/emails'
    | '/admin/media'
    | '/admin/swift-move'
    | '/drive/wallet'
    | '/staff/add'
    | '/swift-move/new'
    | '/api/public/paystack-webhook'
    | '/admin/'
    | '/drive/'
    | '/staff/'
    | '/admin/riders/add'
    | '/admin/staff/add'
    | '/admin/users/create'
    | '/admin/users/permissions'
    | '/admin/users/roles'
    | '/admin/riders/'
    | '/admin/staff/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/community-and-humanitarian'
    | '/contact'
    | '/enterprise-and-ventures'
    | '/impact'
    | '/learn'
    | '/learn-and-develop'
    | '/market'
    | '/media-and-insights'
    | '/partners'
    | '/peace-and-institutional-services'
    | '/reset-password'
    | '/travel'
    | '/travel-and-pilgrimage'
    | '/volunteer'
    | '/what-we-do'
    | '/$'
    | '/apply'
    | '/cart'
    | '/dispatcher'
    | '/driver-dispatch'
    | '/history'
    | '/my-barakah'
    | '/my-impact'
    | '/my-journey'
    | '/my-payments'
    | '/my-support'
    | '/my-swift-move'
    | '/my-vehicle-hires'
    | '/staff-security'
    | '/learn/$slug'
    | '/share/$token'
    | '/travel/$slug'
    | '/admin/dispatcher'
    | '/admin/emails'
    | '/admin/media'
    | '/admin/swift-move'
    | '/drive/wallet'
    | '/staff/add'
    | '/swift-move/new'
    | '/api/public/paystack-webhook'
    | '/admin'
    | '/drive'
    | '/staff'
    | '/admin/riders/add'
    | '/admin/staff/add'
    | '/admin/users/create'
    | '/admin/users/permissions'
    | '/admin/users/roles'
    | '/admin/riders'
    | '/admin/staff'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/community-and-humanitarian'
    | '/contact'
    | '/enterprise-and-ventures'
    | '/impact'
    | '/learn'
    | '/learn-and-develop'
    | '/market'
    | '/media-and-insights'
    | '/partners'
    | '/peace-and-institutional-services'
    | '/reset-password'
    | '/travel'
    | '/travel-and-pilgrimage'
    | '/volunteer'
    | '/what-we-do'
    | '/_authenticated/$'
    | '/_authenticated/apply'
    | '/_authenticated/cart'
    | '/_authenticated/dispatcher'
    | '/_authenticated/driver-dispatch'
    | '/_authenticated/history'
    | '/_authenticated/my-barakah'
    | '/_authenticated/my-impact'
    | '/_authenticated/my-journey'
    | '/_authenticated/my-payments'
    | '/_authenticated/my-support'
    | '/_authenticated/my-swift-move'
    | '/_authenticated/my-vehicle-hires'
    | '/_authenticated/staff-security'
    | '/learn/$slug'
    | '/share/$token'
    | '/travel/$slug'
    | '/_authenticated/admin/dispatcher'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/swift-move'
    | '/_authenticated/drive/wallet'
    | '/_authenticated/staff/add'
    | '/_authenticated/swift-move/new'
    | '/api/public/paystack-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/drive/'
    | '/_authenticated/staff/'
    | '/_authenticated/admin/riders/add'
    | '/_authenticated/admin/staff/add'
    | '/_authenticated/admin/users/create'
    | '/_authenticated/admin/users/permissions'
    | '/_authenticated/admin/users/roles'
    | '/_authenticated/admin/riders/'
    | '/_authenticated/admin/staff/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CommunityAndHumanitarianRoute: typeof CommunityAndHumanitarianRoute
  ContactRoute: typeof ContactRoute
  EnterpriseAndVenturesRoute: typeof EnterpriseAndVenturesRoute
  ImpactRoute: typeof ImpactRoute
  LearnRoute: typeof LearnRouteWithChildren
  LearnAndDevelopRoute: typeof LearnAndDevelopRoute
  MarketRoute: typeof MarketRoute
  MediaAndInsightsRoute: typeof MediaAndInsightsRoute
  PartnersRoute: typeof PartnersRoute
  PeaceAndInstitutionalServicesRoute: typeof PeaceAndInstitutionalServicesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TravelRoute: typeof TravelRouteWithChildren
  TravelAndPilgrimageRoute: typeof TravelAndPilgrimageRoute
  VolunteerRoute: typeof VolunteerRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-and-humanitarian': {
      id: '/community-and-humanitarian'
      path: '/community-and-humanitarian'
      fullPath: '/community-and-humanitarian'
      preLoaderRoute: typeof CommunityAndHumanitarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-and-ventures': {
      id: '/enterprise-and-ventures'
      path: '/enterprise-and-ventures'
      fullPath: '/enterprise-and-ventures'
      preLoaderRoute: typeof EnterpriseAndVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-and-develop': {
      id: '/learn-and-develop'
      path: '/learn-and-develop'
      fullPath: '/learn-and-develop'
      preLoaderRoute: typeof LearnAndDevelopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-and-insights': {
      id: '/media-and-insights'
      path: '/media-and-insights'
      fullPath: '/media-and-insights'
      preLoaderRoute: typeof MediaAndInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peace-and-institutional-services': {
      id: '/peace-and-institutional-services'
      path: '/peace-and-institutional-services'
      fullPath: '/peace-and-institutional-services'
      preLoaderRoute: typeof PeaceAndInstitutionalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-and-pilgrimage': {
      id: '/travel-and-pilgrimage'
      path: '/travel-and-pilgrimage'
      fullPath: '/travel-and-pilgrimage'
      preLoaderRoute: typeof TravelAndPilgrimageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatcher': {
      id: '/_authenticated/dispatcher'
      path: '/dispatcher'
      fullPath: '/dispatcher'
      preLoaderRoute: typeof AuthenticatedDispatcherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver-dispatch': {
      id: '/_authenticated/driver-dispatch'
      path: '/driver-dispatch'
      fullPath: '/driver-dispatch'
      preLoaderRoute: typeof AuthenticatedDriverDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-barakah': {
      id: '/_authenticated/my-barakah'
      path: '/my-barakah'
      fullPath: '/my-barakah'
      preLoaderRoute: typeof AuthenticatedMyBarakahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-impact': {
      id: '/_authenticated/my-impact'
      path: '/my-impact'
      fullPath: '/my-impact'
      preLoaderRoute: typeof AuthenticatedMyImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-journey': {
      id: '/_authenticated/my-journey'
      path: '/my-journey'
      fullPath: '/my-journey'
      preLoaderRoute: typeof AuthenticatedMyJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-payments': {
      id: '/_authenticated/my-payments'
      path: '/my-payments'
      fullPath: '/my-payments'
      preLoaderRoute: typeof AuthenticatedMyPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-support': {
      id: '/_authenticated/my-support'
      path: '/my-support'
      fullPath: '/my-support'
      preLoaderRoute: typeof AuthenticatedMySupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-swift-move': {
      id: '/_authenticated/my-swift-move'
      path: '/my-swift-move'
      fullPath: '/my-swift-move'
      preLoaderRoute: typeof AuthenticatedMySwiftMoveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-vehicle-hires': {
      id: '/_authenticated/my-vehicle-hires'
      path: '/my-vehicle-hires'
      fullPath: '/my-vehicle-hires'
      preLoaderRoute: typeof AuthenticatedMyVehicleHiresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-security': {
      id: '/_authenticated/staff-security'
      path: '/staff-security'
      fullPath: '/staff-security'
      preLoaderRoute: typeof AuthenticatedStaffSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel/$slug': {
      id: '/travel/$slug'
      path: '/$slug'
      fullPath: '/travel/$slug'
      preLoaderRoute: typeof TravelSlugRouteImport
      parentRoute: typeof TravelRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dispatcher': {
      id: '/_authenticated/admin/dispatcher'
      path: '/admin/dispatcher'
      fullPath: '/admin/dispatcher'
      preLoaderRoute: typeof AuthenticatedAdminDispatcherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/swift-move': {
      id: '/_authenticated/admin/swift-move'
      path: '/admin/swift-move'
      fullPath: '/admin/swift-move'
      preLoaderRoute: typeof AuthenticatedAdminSwiftMoveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/wallet': {
      id: '/_authenticated/drive/wallet'
      path: '/drive/wallet'
      fullPath: '/drive/wallet'
      preLoaderRoute: typeof AuthenticatedDriveWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/add': {
      id: '/_authenticated/staff/add'
      path: '/staff/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof AuthenticatedStaffAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swift-move/new': {
      id: '/_authenticated/swift-move/new'
      path: '/swift-move/new'
      fullPath: '/swift-move/new'
      preLoaderRoute: typeof AuthenticatedSwiftMoveNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/riders/': {
      id: '/_authenticated/admin/riders/'
      path: '/admin/riders'
      fullPath: '/admin/riders/'
      preLoaderRoute: typeof AuthenticatedAdminRidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/riders/add': {
      id: '/_authenticated/admin/riders/add'
      path: '/admin/riders/add'
      fullPath: '/admin/riders/add'
      preLoaderRoute: typeof AuthenticatedAdminRidersAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff/': {
      id: '/_authenticated/admin/staff/'
      path: '/admin/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AuthenticatedAdminStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff/add': {
      id: '/_authenticated/admin/staff/add'
      path: '/admin/staff/add'
      fullPath: '/admin/staff/add'
      preLoaderRoute: typeof AuthenticatedAdminStaffAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/create': {
      id: '/_authenticated/admin/users/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AuthenticatedAdminUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/permissions': {
      id: '/_authenticated/admin/users/permissions'
      path: '/admin/users/permissions'
      fullPath: '/admin/users/permissions'
      preLoaderRoute: typeof AuthenticatedAdminUsersPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/roles': {
      id: '/_authenticated/admin/users/roles'
      path: '/admin/users/roles'
      fullPath: '/admin/users/roles'
      preLoaderRoute: typeof AuthenticatedAdminUsersRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDispatcherRoute: typeof AuthenticatedDispatcherRoute
  AuthenticatedDriverDispatchRoute: typeof AuthenticatedDriverDispatchRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMyBarakahRoute: typeof AuthenticatedMyBarakahRoute
  AuthenticatedMyImpactRoute: typeof AuthenticatedMyImpactRoute
  AuthenticatedMyJourneyRoute: typeof AuthenticatedMyJourneyRoute
  AuthenticatedMyPaymentsRoute: typeof AuthenticatedMyPaymentsRoute
  AuthenticatedMySupportRoute: typeof AuthenticatedMySupportRoute
  AuthenticatedMySwiftMoveRoute: typeof AuthenticatedMySwiftMoveRoute
  AuthenticatedMyVehicleHiresRoute: typeof AuthenticatedMyVehicleHiresRoute
  AuthenticatedStaffSecurityRoute: typeof AuthenticatedStaffSecurityRoute
  AuthenticatedAdminDispatcherRoute: typeof AuthenticatedAdminDispatcherRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminSwiftMoveRoute: typeof AuthenticatedAdminSwiftMoveRoute
  AuthenticatedDriveWalletRoute: typeof AuthenticatedDriveWalletRoute
  AuthenticatedStaffAddRoute: typeof AuthenticatedStaffAddRoute
  AuthenticatedSwiftMoveNewRoute: typeof AuthenticatedSwiftMoveNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedAdminRidersAddRoute: typeof AuthenticatedAdminRidersAddRoute
  AuthenticatedAdminStaffAddRoute: typeof AuthenticatedAdminStaffAddRoute
  AuthenticatedAdminUsersCreateRoute: typeof AuthenticatedAdminUsersCreateRoute
  AuthenticatedAdminUsersPermissionsRoute: typeof AuthenticatedAdminUsersPermissionsRoute
  AuthenticatedAdminUsersRolesRoute: typeof AuthenticatedAdminUsersRolesRoute
  AuthenticatedAdminRidersIndexRoute: typeof AuthenticatedAdminRidersIndexRoute
  AuthenticatedAdminStaffIndexRoute: typeof AuthenticatedAdminStaffIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedApplyRoute: AuthenticatedApplyRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDispatcherRoute: AuthenticatedDispatcherRoute,
  AuthenticatedDriverDispatchRoute: AuthenticatedDriverDispatchRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMyBarakahRoute: AuthenticatedMyBarakahRoute,
  AuthenticatedMyImpactRoute: AuthenticatedMyImpactRoute,
  AuthenticatedMyJourneyRoute: AuthenticatedMyJourneyRoute,
  AuthenticatedMyPaymentsRoute: AuthenticatedMyPaymentsRoute,
  AuthenticatedMySupportRoute: AuthenticatedMySupportRoute,
  AuthenticatedMySwiftMoveRoute: AuthenticatedMySwiftMoveRoute,
  AuthenticatedMyVehicleHiresRoute: AuthenticatedMyVehicleHiresRoute,
  AuthenticatedStaffSecurityRoute: AuthenticatedStaffSecurityRoute,
  AuthenticatedAdminDispatcherRoute: AuthenticatedAdminDispatcherRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminSwiftMoveRoute: AuthenticatedAdminSwiftMoveRoute,
  AuthenticatedDriveWalletRoute: AuthenticatedDriveWalletRoute,
  AuthenticatedStaffAddRoute: AuthenticatedStaffAddRoute,
  AuthenticatedSwiftMoveNewRoute: AuthenticatedSwiftMoveNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedAdminRidersAddRoute: AuthenticatedAdminRidersAddRoute,
  AuthenticatedAdminStaffAddRoute: AuthenticatedAdminStaffAddRoute,
  AuthenticatedAdminUsersCreateRoute: AuthenticatedAdminUsersCreateRoute,
  AuthenticatedAdminUsersPermissionsRoute:
    AuthenticatedAdminUsersPermissionsRoute,
  AuthenticatedAdminUsersRolesRoute: AuthenticatedAdminUsersRolesRoute,
  AuthenticatedAdminRidersIndexRoute: AuthenticatedAdminRidersIndexRoute,
  AuthenticatedAdminStaffIndexRoute: AuthenticatedAdminStaffIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface TravelRouteChildren {
  TravelSlugRoute: typeof TravelSlugRoute
}

const TravelRouteChildren: TravelRouteChildren = {
  TravelSlugRoute: TravelSlugRoute,
}

const TravelRouteWithChildren =
  TravelRoute._addFileChildren(TravelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CommunityAndHumanitarianRoute: CommunityAndHumanitarianRoute,
  ContactRoute: ContactRoute,
  EnterpriseAndVenturesRoute: EnterpriseAndVenturesRoute,
  ImpactRoute: ImpactRoute,
  LearnRoute: LearnRouteWithChildren,
  LearnAndDevelopRoute: LearnAndDevelopRoute,
  MarketRoute: MarketRoute,
  MediaAndInsightsRoute: MediaAndInsightsRoute,
  PartnersRoute: PartnersRoute,
  PeaceAndInstitutionalServicesRoute: PeaceAndInstitutionalServicesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TravelRoute: TravelRouteWithChildren,
  TravelAndPilgrimageRoute: TravelAndPilgrimageRoute,
  VolunteerRoute: VolunteerRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
